sudo: required
dist: trusty

language: c

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: GCCVER=6 TESTENV=c
    - os: linux
      env: TESTENV=stack-linux
    - os: windows
      env: TESTENV=stack-windows
    - os: osx
      osx_image: xcode10.3
      env: TESTENV=stack-osx

cache:
  apt: true
  directories:
    - $HOME/.stack/

before_install:
  # Install stack
  - if [[ "$TESTENV" == "stack-linux" ]]; then
      mkdir -p $HOME/.local/bin $HOME/.local/include $HOME/.local/lib;
      export PATH=~/.local/bin:$PATH;
      export LD_LIBRARY_PATH=$HOME/.local/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH};
      travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 \
        | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack';
    fi
  - if [[ "$TESTENV" == "stack-osx" ]]; then
      mkdir -p $HOME/.local/bin $HOME/.local/include $HOME/.local/lib;
      export PATH=~/.local/bin:$PATH;
      export DYLD_LIBRARY_PATH=$HOME/.local/lib${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH};
      brew install haskell-stack;
    fi
  - if [[ "$TESTENV" == "c" ]]; then
      export CC=gcc-$GCCVER;
      export CXX=g++-$GCCVER;
      export C_COMPILER=$CC;
      export CXX_COMPILER=$CXX;
      $CC --version;
      $CXX --version;
    fi
  - if [[ "$TESTENV" == "stack-windows" ]]; then
      choco install haskell-stack;
    fi

script:
  - bash ./travis.sh

  - if [[ "$TESTENV" == "stack-windows" ]] && [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      cp $HOME/AppData/Roaming/local/bin/json2rtcm3.exe .;
      cp $HOME/AppData/Roaming/local/bin/rtcm32json.exe .;
      7z a -tzip librtcm_windows.zip json2rtcm3.exe rtcm32json.exe;
      VERSION="$(git describe --always --tags)";
      mv librtcm_windows.zip "librtcm-${VERSION}-windows-x86_64.zip";
      ls -l;
    fi

  - if [[ "$TESTENV" == "stack-osx" ]] && [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      cp ~/.local/bin/json2rtcm3 .;
      cp ~/.local/bin/rtcm32json .;
      tar -czf librtcm_macos.tar.gz json2rtcm3 rtcm32json;
      VERSION="$(git describe --always --tags)";
      mv librtcm_macos.tar.gz "librtcm-${VERSION}-macos-x86_64.tar.gz";
      ls -l;
    fi

  - if [[ "$TESTENV" == "stack-linux" ]] && [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      cp ~/.local/bin/json2rtcm3 .;
      cp ~/.local/bin/rtcm32json .;
      tar -czf librtcm_linux.tar.gz json2rtcm3 rtcm32json;
      VERSION="$(git describe --always --tags)";
      mv librtcm_linux.tar.gz "librtcm-${VERSION}-linux-x86_64.tar.gz";
      ls -l;
    fi


_github_api_key: &_github_api_key
  api_key:
    secure: "ZsUAu8jCzyth0T97ESlUAflFZgn7XMsuA02jdZ7uIYUCCiUmkXB9FRCjS7iNrgGKdKO5MLHiLQUyoRoqkRsSKNTAGRUpQHGukqXy4+vMLvRmjk/JfdWG4nMZO/3DtzJPE0sYqapXgbEkQSKwzf+wo5F9m7fr1gNXWKUjx2s/eazraxt4CZ7f8KsdhXKE93myI0AzFmPDzEKcT5PaCylAZRv8L3KZclIWk1IsbBjmI1sTMcwrqCgzxfyF+ijgwiN8MKImAJSHXuncdDpW1h0NfUW05RRIwS7WVy3U31u4e8BX7+GLSrMA7TZQzPYuf+CHGM79Cay9lG27ObGCPzvaM2i8V6vdMYV+JE/K6JwFh2v0LFnn426S3RbSnJfSNnY/XeeE7wLFhybPSyyH8LC+tYcNI1EQEUjIu68ThWFlaMosDEh62XdZPQoSA34gUoGkCijzxCBJiFGWt35wCFb+ee8gwIlM7JlODxpmaudVBj5eQxd5La0Ya4DXB5S9oTOUY+qtZ5Bl7WR5B7aqfpOJBVpABRmt1usyPZ+IpQH+XCd/S5DhA4f+erXgfbQhri6d7BeuLMWB9OoX2jWcMaWl60lPL+OgsxmNrzLa9ZyFr9f4+/y+vvIG7GmKTGqKifBw3fhXKTja+lMJsPtLNPF1v0uBDCh5ovhIl/kpVqo8cug="

deploy:
  - provider: releases
    file_glob: true
    file: "librtcm-*windows*.zip"
    skip_cleanup: true
    "on":
      tags: true
      condition: "$TRAVIS_OS_NAME = windows"
    <<: *_github_api_key
  - provider: releases
    file_glob: true
    file: "librtcm-*macos*.tar.gz"
    skip_cleanup: true
    "on":
      tags: true
      condition: "$TRAVIS_OS_NAME = osx"
    <<: *_github_api_key
  - provider: releases
    file_glob: true
    file: "librtcm-*linux*.tar.gz"
    skip_cleanup: true
    "on":
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
    <<: *_github_api_key
